#!/bin/bash

NGINX_TOOLS_PATH=$(cd $(dirname $0); pwd)
source "$NGINX_TOOLS_PATH/env.sh"

sitename=$1
if [ ! -e "$NGINX_CONFIG_PATH/sites-enabled/$sitename" ]; then
	echo "WARNING: Site $sitename is not enabled yet."
	exit 0
fi
if [ ! -L "$NGINX_CONFIG_PATH/sites-enabled/$sitename" ]; then
	echo "ERROR: $NGINX_CONFIG_PATH/sites-enabled/$sitename is not a symbol link"
	exit 1
fi

rm -f "$NGINX_CONFIG_PATH/sites-enabled/$sitename"
retcode=$?
if [[ $retcode != 0 ]]; then
	echo "FAILED: $retcode"
	exit $retcode
fi

echo echo "Site $sitename disabled."

